apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pythontemplate
  janus-idp.io/tekton: pythontemplate
  backstage.io/kubernetes-id: pythontemplate
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pythontemplate
resources:
- deployment.yaml
- route.yaml
- service.yaml
